include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  language:
    strict-inference: true
  errors:
    missing_required_param: error
linter:
  rules:
    avoid_print: false
    constant_identifier_names: false
